@startuml ShareYASHE - Deployment structure - ShareYASHE server
left to right direction

actor "User" as user

cloud {
    artifact "ShareYASHE\nHTTP server" as httpServer {
    }
    artifact "ShareYASHE\nWebSocket server" as wsServer {
    }
    database "Documents\ndatabase" as db {
    }
}

user -left-> httpServer
user -left-> wsServer

httpServer -down-> db
wsServer -down-> db

@enduml