name: ShareYASHE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm start
        env:
          SHAREYASHE_CRYPTO_KEY: ${{ secrets.SHAREYASHE_CRYPTO_KEY }}
          SHAREYASHE_MONGODB: ${{ secrets.SHAREYASHE_MONGODB }}
